# Why we use numpy

In [ ]:
# Normal python
import time
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]
c =[]

start = time.time()
for i in range(len(a)):  #need to list to calculate one by one
    c.append(a[i]*b[i])
print(time.time() - start)

1.230151891708374


In [ ]:
#using same thing Numpy
import numpy as np

a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time() - start)

0.09168529510498047


In [ ]:
#Differnece is shocking,numpy faster than normal python by 10 times
1.9060945510864258/0.17719292640686035



In [ ]:
a = np.arange(10000000,dtype=np.int32)
import sys
sys.getsizeof(a)


40000112

#Adavanced Indexing

In [ ]:
# fancy indexing
a = np.arange(24).reshape(6,4)
print(a)

a[[0,1,5]]  # for the rows


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [20, 21, 22, 23]])

In [ ]:
a[:,[0,2,3]]  # for the column

In [ ]:
# Boolean Indexinng

a = np.random.randint(1,100,30).reshape(6,5)
a

In [ ]:
# find all number greater than 50

a[a >= 50]

In [ ]:
# find out even numbers


a[a % 2== 0]

In [ ]:
# find all number greater than 50 and even

a[(a > 50) & (a % 2 == 0)]

In [1]:
# find all numbers that not dividable by 7

a[a % 7 != 0]

a[~(a % 7 == 0)]
# both are useful for this condition

NameError: name 'a' is not defined

# Broadcasting

The term broadcasting describe how Numpy treats arrays with different shapes during aruthmentic operations.

The smaller array is "broadcast" across the larger array to so that they have commplatiable shapes.



In [ ]:
# same shape
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)

print(a)
print(b)

print("\n",a + b)

In [ ]:
# diff shape

a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print("\n",a + b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]

 [[0 2 4]
 [3 5 7]]


In [ ]:
#Some practise of broadcasting

a = np.arange(12).reshape(4,3)
b = np.arange(3).reshape(3)

print(a)
print(b)

print("\n", a + b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]

 [[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]
 [ 9 11 13]]


In [ ]:

a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

print(a)
print(b)

print("\n", a + b)

[[0 1 2]]
[[0]
 [1]
 [2]]

 [[0 1 2]
 [1 2 3]
 [2 3 4]]


In [ ]:

a = np.arange(4).reshape(4,1)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print("\n", a + b)

[[0]
 [1]
 [2]
 [3]]
[[0 1 2]]

 [[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]]


In [ ]:

a = np.arange(1)
b = np.arange(4).reshape(2,2)

print(a)
print(b)

print("\n", a + b)

[0]
[[0 1]
 [2 3]]

 [[0 1]
 [2 3]]


In [ ]:
#This don't work because we need 1 in on of the range of array
a = np.arange(12).reshape(4,3)
b = np.arange(12).reshape(3,4)

print(a)
print(b)

print("\n", a + b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


ValueError: operands could not be broadcast together with shapes (4,3) (3,4) 

In [ ]:
#This don't work because we need 1 in on of the range of array

a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)

print(a)
print(b)

print("\n", a + b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

##Working with mathematical formulas

In [ ]:
#sigmoid

def sigmoid(array):
  return 1/(1 + np.exp(-array))

a = np.arange(10)

sigmoid(a)


array([0.5       , 0.73105858, 0.88079708, 0.95257413, 0.98201379,
       0.99330715, 0.99752738, 0.99908895, 0.99966465, 0.99987661])

In [ ]:
#mean squered error

actual = np.random.randint(1,20,10)
predict = np.random.randint(1,20,10)

def mse(actual,predict):
  return np.mean((actual - predict)**2)

mse(actual,predict)

np.float64(42.2)

In [ ]:
#categorical cross entropy