# Why we use numpy

In [ ]:
# Normal python
import time
a = [i for i in range(10000000)]
b = [i for i in range(10000000,20000000)]
c =[]

start = time.time()
for i in range(len(a)):  #need to list to calculate one by one
    c.append(a[i]*b[i])
print(time.time() - start)

1.9312691688537598


In [ ]:
#using same thing Numpy
import numpy as np

a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time() - start)

0.15459370613098145


In [ ]:
#Differnece is shocking,numpy faster than normal python by 10 times
1.9060945510864258/0.17719292640686035



10.75717067119124

In [ ]:
a = np.arange(10000000,dtype=np.int32)
import sys
sys.getsizeof(a)


40000112

#Adavanced Indexing

In [ ]:
# fancy indexing
a = np.arange(24).reshape(6,4)
print(a)

a[[0,1,5]]  # for the rows


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [20, 21, 22, 23]])

In [ ]:
a[:,[0,2,3]]  # for the column

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11],
       [12, 14, 15],
       [16, 18, 19],
       [20, 22, 23]])

In [ ]:
# Boolean Indexinng

a = np.random.randint(1,100,30).reshape(6,5)
a

array([[25, 10, 50, 38, 20],
       [26, 27, 70, 13,  1],
       [29, 54, 51, 26, 24],
       [80, 85, 43, 56, 18],
       [70, 99, 56, 93, 14],
       [68, 26, 21, 59, 85]])

In [ ]:
# find all number greater than 50

a[a >= 50]

array([50, 70, 54, 51, 80, 85, 56, 70, 99, 56, 93, 68, 59, 85])

In [ ]:
# find out even numbers


a[a % 2== 0]

array([10, 50, 38, 20, 26, 70, 54, 26, 24, 80, 56, 18, 70, 56, 14, 68, 26])

In [ ]:
# find all number greater than 50 and even

a[(a > 50) & (a % 2 == 0)]

array([70, 54, 80, 56, 70, 56, 68])

In [ ]:
# find all numbers that not dividable by 7

a[a % 7 != 0]

a[~(a % 7 == 0)]
# both are useful for this condition

array([25, 10, 50, 38, 20, 26, 27, 13,  1, 29, 54, 51, 26, 24, 80, 85, 43,
       18, 99, 93, 68, 26, 59, 85])

# Broadcasting

The term broadcasting describe how Numpy treats arrays with different shapes during aruthmentic operations.

The smaller array is "broadcast" across the larger array to so that they have commplatiable shapes.



In [ ]:
# same shape
a = np.arange(6).reshape(3,2)
b = np.arange(6,12).reshape(3,2)

print(a)
print(b)

print("\n",a + b)

[[0 1]
 [2 3]
 [4 5]]
[[ 6  7]
 [ 8  9]
 [10 11]]

 [[ 6  8]
 [10 12]
 [14 16]]


In [ ]:
# diff shape

a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print("\n",a + b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]

 [[0 2 4]
 [3 5 7]]
